spring:
    application:
        name: spring-batch-mysql-gradle

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: admin
        url: jdbc:mysql://localhost:3306/springbatchdb?createDatabaseIfNotExist=true

    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update # Options: none, update, create, create-drop
      properties:
        dialect: org.hibernate.dialect.MySQL8Dialect

    batch:
      job:
        enabled: false #Disable job run at startup
      #    The initialize-schema property controls when Spring Batch should initialize or reinitialize the schema used for batch processing metadata tables.
      #    These tables store information about job executions, step executions, and other related metadata.
      #    ALWAYS: Spring Batch will always initialize (or reinitialize) the schema.
      #    NEVER: Spring Batch will never initialize or modify the schema.
      #    IF_ABSENT: Spring Batch will only initialize the schema if it does not already exist.
      jdbc:
        initialize-schema: always # related to initialize schema